# Generated by Django 4.1.6 on 2023-03-17 08:01

from django.db import migrations, models

# python manage.py sqlmigrate event 0001
# manage.py migrate
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desctiption', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('type', models.BooleanField(verbose_name='Тип')),
                ('logo', models.ImageField(max_length=50, upload_to='', verbose_name='Логотип')),
                ('data_event', models.DateField(null=True, verbose_name='Дата')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('city', models.TextField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('age', models.FloatField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('sex', models.CharField(max_length=4, verbose_name='Пол')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
            ],
        ),
    ]
